S C:\Users\zhu\Downloads\stage.docker-main> python manage.py migrate --fake restaurant zero
System check identified some issues:

WARNINGS:
?: (2_0.W001) Your URL pattern '^admin/' has a route that contains '(?P<', begins with a '^', or ends with a '$'. This was likely an oversight when migrating to django.urls.path().
?: (urls.W005) URL namespace 'admin' isn't unique. You may not be able to reverse all URLs in this namespace
Operations to perform:
  Unapply all migrations: restaurant
Running migrations:
  Rendering model states... DONE
  Unapplying restaurant.0005_order_completed_at_alter_order_status... FAKED
  Unapplying restaurant.0004_order_user_alter_order_prix... FAKED
  Unapplying restaurant.0003_order_updated_at... FAKED
  Unapplying restaurant.0002_auto_20240417_1721... FAKED
  Unapplying restaurant.0001_initial... FAKED
PS C:\Users\zhu\Downloads\stage.docker-main> python manage.py migrate restaurant            
System check identified some issues:

WARNINGS:
?: (2_0.W001) Your URL pattern '^admin/' has a route that contains '(?P<', begins with a '^', or ends with a '$'. This was likely an oversight when migrating to django.urls.path().
?: (urls.W005) URL namespace 'admin' isn't unique. You may not be able to reverse all URLs in this namespace
Operations to perform:
  Apply all migrations: restaurant
Running migrations:
  Applying restaurant.0001_initial...Traceback (most recent call last):
  File "C:\Users\zhu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 103, in _execute
    return self.cursor.execute(sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.DuplicateTable: 错误:  关系 "restaurant_category" 已经存在


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\zhu\Downloads\stage.docker-main\manage.py", line 22, in <module>
    main()
  File "C:\Users\zhu\Downloads\stage.docker-main\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\zhu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "C:\Users\zhu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\management\__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\zhu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\management\base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\zhu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\management\base.py", line 459, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zhu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\management\base.py", line 107, in wrapper
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zhu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\management\commands\migrate.py", line 356, in handle
    post_migrate_state = executor.migrate(
                         ^^^^^^^^^^^^^^^^^
  File "C:\Users\zhu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\migrations\executor.py", line 135, in migrate
    state = self._migrate_all_forwards(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zhu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\migrations\executor.py", line 167, in _migrate_all_forwards
    state = self.apply_migration(
            ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zhu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\migrations\executor.py", line 252, in apply_migration
    state = migration.apply(state, schema_editor)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zhu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\migrations\migration.py", line 132, in apply
    operation.database_forwards(
  File "C:\Users\zhu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\migrations\operations\models.py", line 96, in database_forwards
    schema_editor.create_model(model)
  File "C:\Users\zhu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\base\schema.py", line 488, in create_model
    self.execute(sql, params or None)
  File "C:\Users\zhu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\postgresql\schema.py", line 45, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zhu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\base\schema.py", line 201, in execute
    cursor.execute(sql, params)
  File "C:\Users\zhu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zhu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zhu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zhu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\zhu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\utils.py", line 91, in __exit__ 
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\zhu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 103, in _execute
    return self.cursor.execute(sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: 错误:  关系 "restaurant_category" 已经存在

PS C:\Users\zhu\Downloads\stage.docker-main> 
